#cloud-config
chpasswd: { expire: False }

package_update: true
package_upgrade: true
packages:
  - conntrack
  - ipset
  - iputils-ping
  - socat


runcmd:
  - touch /etc/cloud/cloud-init.disabled

ssh_authorized_keys:
{%- for key in ssh_keys %}
  - "{{ key }}"
{%- endfor %}

ssh_pwauth: True

hostname: {{ hostname }}
fqdn: {{ fqdn }}
manage_etc_hosts: True
