#cloud-config
password: xKdqOAX4AiZ4g0Zcm7kH
chpasswd: { expire: False }

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - conntrack
  - emacs-nox
  - ipset
  - iputils-ping
  - socat


runcmd:
  - touch /etc/cloud/cloud-init.disabled

ssh_authorized_keys:
{%- for key in ssh_keys %}
  - "{{ key }}"
{%- endfor %}

ssh_pwauth: True

hostname: {{ hostname }}
fqdn: {{ fqdn }}
manage_etc_hosts: True
final_message: "The system is up after $UPTIME seconds"
